app = "hackerspub"
primary_region = "nrt"

[deploy]
release_command = "deno task migrate"

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "10s"
path = "/"

[[vm]]
memory = "1gb"
cpu_kind = "shared"
cpus = 1
